version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb_wallpaper
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hello
      - MONGO_INITDB_ROOT_PASSWORD=bye
    volumes:
      - ./mongodata:/mongodata
    ports:
      - "27017:27017"

  springboot:
    build: .
    container_name: wallpaper_service
    depends_on:
      - mongodb
    ports:
      - "80:8088"